export const ADD_RECEPIE = 'ADD_RECEPIE'
export const SET_DISH_TYPE = 'SET_DISH_TYPE'
export const ADD_RECEPIE_ERROR = 'ADD_RECEPIE_ERROR'
export const SET_VALIDATION_ERRORS = 'SET_VALIDATION_ERRORS'
